<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>add_to_cart_btn</description>
   <name>add_to_cart</name>
   <tag></tag>
   <elementGuidId>0f3f1552-3928-41ac-89f2-1cf74deb38b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-to-cart-button']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
